--------------------------------------------------------
--  DDL for Package Body W4PKG_DATA_SYNC
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE BODY "T24IBS"."W4PKG_DATA_SYNC" 
IS
/*----------------------------------------------------------------------------------------------------
 ** Module   : ODS SYSTEM
 ** and is copyrighted by FSS.
 **
 **    All rights reserved.  No part of this work may be reproduced, stored in a retrieval system,
 **    adopted or transmitted in any form or by any means, electronic, mechanical, photographic,
 **    graphic, optic recording or otherwise, translated in any language or computer language,
 **    without the prior written permission of Financial Software Solutions. JSC.
 **
 **  MODIFICATION HISTORY
 **  Person      Date           Comments
 **  ThanhNT      23-01-2015    Created
 ** (c) 2014 by Financial Software Solutions. JSC.
 ----------------------------------------------------------------------------------------------------*/

   -- pkgctx    plog.log_ctx;
  --  logrow    tlogdebug%ROWTYPE;

 /*----------------------------------------------------------------------------------------------------
 **  Description:
 **
 **  MODIFICATION HISTORY
 **  Person      Date           Comments
 **  ThanhNT      23/01/2015    Created

----------------------------------------------------------------------------------------------------*/

    PROCEDURE pr_client_sync (dm_operation_type            IN CHAR,
                            orchestrate_amnd_state         IN VARCHAR2,
                            orchestrate_amnd_date          IN DATE,
                            orchestrate_amnd_officer       IN NUMBER,
                            orchestrate_amnd_prev          IN NUMBER,
                            orchestrate_id                 IN NUMBER,
                            orchestrate_f_i                IN NUMBER,
                            orchestrate_branch             IN VARCHAR2,
                            orchestrate_ccat               IN VARCHAR2,
                            orchestrate_pcat               IN VARCHAR2,
                            orchestrate_clt                IN NUMBER,
                            orchestrate_service_group      IN VARCHAR2,
                            orchestrate_short_name         IN VARCHAR2,
                            orchestrate_title              IN NUMBER,
                            orchestrate_first_nam          IN VARCHAR2,
                            orchestrate_father_s_nam       IN VARCHAR2,
                            orchestrate_last_nam           IN VARCHAR2,
                            orchestrate_birth_nam          IN VARCHAR2,
                            orchestrate_mother_s_nam       IN VARCHAR2,
                            orchestrate_birth_date         IN DATE,
                            orchestrate_birth_place        IN VARCHAR2,
                            orchestrate_citizenship        IN VARCHAR2,
                            orchestrate_company_nam        IN VARCHAR2,
                            orchestrate_trade_nam          IN VARCHAR2,
                            orchestrate_url                IN VARCHAR2,
                            orchestrate_company_department IN VARCHAR2,
                            orchestrate_profession         IN VARCHAR2,
                            orchestrate_enable_affiliation IN VARCHAR2,
                            orchestrate_affiliated_with    IN NUMBER,
                            orchestrate_reg_number_type    IN VARCHAR2,
                            orchestrate_reg_number         IN VARCHAR2,
                            orchestrate_reg_details        IN VARCHAR2,
                            orchestrate_affiliation_type   IN VARCHAR2,
                            orchestrate_client_number      IN VARCHAR2,
                            orchestrate_itn                IN VARCHAR2,
                            orchestrate_tax_position       IN VARCHAR2,
                            orchestrate_country            IN VARCHAR2,
                            orchestrate_state              IN VARCHAR2,
                            orchestrate_city               IN VARCHAR2,
                            orchestrate_address_zip        IN VARCHAR2,
                            orchestrate_address_line_1     IN VARCHAR2,
                            orchestrate_address_line_2     IN VARCHAR2,
                            orchestrate_address_line_3     IN VARCHAR2,
                            orchestrate_address_line_4     IN VARCHAR2,
                            orchestrate_phone              IN VARCHAR2,
                            orchestrate_phone_h            IN VARCHAR2,
                            orchestrate_phone_m            IN VARCHAR2,
                            orchestrate_fax                IN VARCHAR2,
                            orchestrate_fax_h              IN VARCHAR2,
                            orchestrate_e_mail             IN VARCHAR2,
                            orchestrate_delivery_type      IN NUMBER,
                            orchestrate_date_expire        IN DATE,
                            orchestrate_date_open          IN DATE,
                            orchestrate_gender             IN VARCHAR2,
                            orchestrate_language           IN NUMBER,
                            orchestrate_marital_status     IN NUMBER,
                            orchestrate_tr_title           IN NUMBER,
                            orchestrate_tr_first_nam       IN VARCHAR2,
                            orchestrate_tr_last_nam        IN VARCHAR2,
                            orchestrate_tr_company_nam     IN VARCHAR2,
                            orchestrate_add_date_01        IN DATE,
                            orchestrate_add_date_02        IN DATE,
                            orchestrate_add_info_01        IN VARCHAR2,
                            orchestrate_add_info_02        IN VARCHAR2,
                            orchestrate_add_info_03        IN VARCHAR2,
                            orchestrate_add_info_04        IN VARCHAR2,
                            orchestrate_is_ready           IN VARCHAR2,
                            orchestrate_before_id          IN NUMBER)
    IS
        l_check NUMBER(2);
        l_err_desc VARCHAR2(250);

    BEGIN

        IF orchestrate_amnd_state = 'A' THEN
            IF dm_operation_type <> 'D'
            THEN
                --Todo: Check xem client nay co thuoc CIF tren EBANK khong?
                SELECT CASE WHEN EXISTS(SELECT 1 FROM ( SELECT cif_no
                                                        FROM bc_user_info
                                                        UNION
                                                        SELECT cif_no
                                                        FROM bb_corp_info) a
                                        WHERE a.cif_no = orchestrate_client_number)
                            THEN 1
                            ELSE 0
                        END
                INTO l_check FROM dual;

                --Todo: Merge thong tin

                IF l_check = 1 THEN
                    MERGE INTO   sync_way4_client c
                    USING   (SELECT orchestrate_amnd_state         AS amnd_state,
                                    orchestrate_amnd_date          AS amnd_date,
                                    orchestrate_amnd_officer       AS amnd_officer  ,
                                    orchestrate_amnd_prev          AS amnd_prev  ,
                                    orchestrate_id                 AS id,
                                    orchestrate_f_i                AS f_i,
                                    orchestrate_branch             AS branch,
                                    orchestrate_ccat               AS ccat,
                                    orchestrate_pcat               AS pcat,
                                    orchestrate_clt                AS clt,
                                    orchestrate_service_group      AS service_group,
                                    orchestrate_short_name         AS short_name,
                                    orchestrate_title              AS title,
                                    orchestrate_first_nam          AS first_nam,
                                    orchestrate_father_s_nam       AS father_s_nam,
                                    orchestrate_last_nam           AS last_nam,
                                    orchestrate_birth_nam          AS birth_nam,
                                    orchestrate_mother_s_nam       AS mother_s_nam,
                                    orchestrate_birth_date         AS birth_date,
                                    orchestrate_birth_place        AS birth_place,
                                    orchestrate_citizenship        AS citizenship,
                                    orchestrate_company_nam        AS company_nam,
                                    orchestrate_trade_nam          AS trade_nam,
                                    orchestrate_url                AS url,
                                    orchestrate_company_department AS company_department,
                                    orchestrate_profession         AS profession,
                                    orchestrate_enable_affiliation AS enable_affiliation,
                                    orchestrate_affiliated_with    AS affiliated_with,
                                    orchestrate_reg_number_type    AS reg_number_type,
                                    orchestrate_reg_number         AS reg_number,
                                    orchestrate_reg_details        AS reg_details,
                                    orchestrate_affiliation_type   AS affiliation_type,
                                    orchestrate_client_number      AS client_number,
                                    orchestrate_itn                AS itn,
                                    orchestrate_tax_position       AS tax_position,
                                    orchestrate_country            AS country,
                                    orchestrate_state              AS state,
                                    orchestrate_city               AS city,
                                    orchestrate_address_zip        AS address_zip,
                                    orchestrate_address_line_1     AS address_line_1,
                                    orchestrate_address_line_2     AS address_line_2,
                                    orchestrate_address_line_3     AS address_line_3,
                                    orchestrate_address_line_4     AS address_line_4,
                                    orchestrate_phone              AS phone,
                                    orchestrate_phone_h            AS phone_h,
                                    orchestrate_phone_m            AS phone_m,
                                    orchestrate_fax                AS fax,
                                    orchestrate_fax_h              AS fax_h,
                                    orchestrate_e_mail             AS e_mail,
                                    orchestrate_delivery_type      AS delivery_type,
                                    orchestrate_date_expire        AS date_expire ,
                                    orchestrate_date_open          AS date_open,
                                    orchestrate_gender             AS gender,
                                    orchestrate_language           AS language,
                                    orchestrate_marital_status     AS marital_status,
                                    orchestrate_tr_title           AS tr_title,
                                    orchestrate_tr_first_nam       AS tr_first_nam,
                                    orchestrate_tr_last_nam        AS tr_last_nam,
                                    orchestrate_tr_company_nam     AS tr_company_nam,
                                    orchestrate_add_date_01        AS add_date_01,
                                    orchestrate_add_date_02        AS add_date_02,
                                    orchestrate_add_info_01        AS add_info_01,
                                    orchestrate_add_info_02        AS add_info_02,
                                    orchestrate_add_info_03        AS add_info_03,
                                    orchestrate_add_info_04        AS add_info_04,
                                    orchestrate_is_ready           AS is_ready
                            FROM   DUAL) src
                    ON   (c.id = src.id)
                    WHEN MATCHED THEN
                    UPDATE
                    SET c.amnd_state = src.amnd_state,
                        c.amnd_date = src.amnd_date,
                        c.amnd_officer = src.amnd_officer,
                        c.amnd_prev = src.amnd_prev,
                        c.f_i = src.f_i,
                        c.branch = src.branch,
                        c.ccat = src.ccat,
                        c.pcat = src.pcat,
                        c.clt = src.clt,
                        c.service_group = src.service_group,
                        c.short_name = src.short_name,
                        c.title = src.title,
                        c.first_nam = src.first_nam,
                        c.father_s_nam = src.father_s_nam,
                        c.last_nam = src.last_nam,
                        c.birth_nam = src.birth_nam,
                        c.mother_s_nam = src.mother_s_nam,
                        c.birth_date = src.birth_date,
                        c.birth_place = src.birth_place,
                        c.citizenship = src.citizenship,
                        c.company_nam = src.company_nam,
                        c.trade_nam = src.trade_nam,
                        c.url = src.url,
                        c.company_department = src.company_department,
                        c.profession = src.profession,
                        c.enable_affiliation = src.enable_affiliation,
                        c.affiliated_with = src.affiliated_with,
                        c.reg_number_type = src.reg_number_type,
                        c.reg_number = src.reg_number,
                        c.reg_details = src.reg_details,
                        c.affiliation_type = src.affiliation_type,
                        c.client_number = src.client_number,
                        c.itn = src.itn,
                        c.tax_position = src.tax_position,
                        c.country = src.country,
                        c.state = src.state,
                        c.city = src.city,
                        c.address_zip = src.address_zip,
                        c.address_line_1 = src.address_line_1,
                        c.address_line_2 = src.address_line_2,
                        c.address_line_3 = src.address_line_3,
                        c.address_line_4 = src.address_line_4,
                        c.phone = src.phone,
                        c.phone_h = src.phone_h,
                        c.phone_m = src.phone_m,
                        c.fax = src.fax,
                        c.fax_h = src.fax_h,
                        c.e_mail = src.e_mail,
                        c.delivery_type = src.delivery_type,
                        c.date_expire = src.date_expire,
                        c.date_open = src.date_open,
                        c.gender = src.gender,
                        c.language = src.language,
                        c.marital_status = src.marital_status,
                        c.tr_title = src.tr_title,
                        c.tr_first_nam = src.tr_first_nam,
                        c.tr_last_nam = src.tr_last_nam,
                        c.tr_company_nam = src.tr_company_nam,
                        c.add_date_01 = src.add_date_01,
                        c.add_date_02 = src.add_date_02,
                        c.add_info_01 = src.add_info_01,
                        c.add_info_02 = src.add_info_02,
                        c.add_info_03 = src.add_info_03,
                        c.add_info_04 = src.add_info_04,
                        c.is_ready = src.is_ready
                    WHEN NOT MATCHED
                    THEN
                        INSERT (amnd_state,
                                amnd_date,
                                amnd_officer,
                                amnd_prev,
                                id,
                                f_i,
                                branch,
                                ccat,
                                pcat,
                                clt,
                                service_group,
                                short_name,
                                title,
                                first_nam,
                                father_s_nam,
                                last_nam,
                                birth_nam,
                                mother_s_nam,
                                birth_date,
                                birth_place,
                                citizenship,
                                company_nam,
                                trade_nam,
                                url,
                                company_department,
                                profession,
                                enable_affiliation,
                                affiliated_with,
                                reg_number_type,
                                reg_number,
                                reg_details,
                                affiliation_type,
                                client_number,
                                itn,
                                tax_position,
                                country,
                                state,
                                city,
                                address_zip,
                                address_line_1,
                                address_line_2,
                                address_line_3,
                                address_line_4,
                                phone,
                                phone_h,
                                phone_m,
                                fax,
                                fax_h,
                                e_mail,
                                delivery_type,
                                date_expire,
                                date_open,
                                gender,
                                language,
                                marital_status,
                                tr_title,
                                tr_first_nam,
                                tr_last_nam,
                                tr_company_nam,
                                add_date_01,
                                add_date_02,
                                add_info_01,
                                add_info_02,
                                add_info_03,
                                add_info_04,
                                is_ready)
                        VALUES (src.amnd_state,
                                src.amnd_date,
                                src.amnd_officer,
                                src.amnd_prev,
                                src.id,
                                src.f_i,
                                src.branch,
                                src.ccat,
                                src.pcat,
                                src.clt,
                                src.service_group,
                                src.short_name,
                                src.title,
                                src.first_nam,
                                src.father_s_nam,
                                src.last_nam,
                                src.birth_nam,
                                src.mother_s_nam,
                                src.birth_date,
                                src.birth_place,
                                src.citizenship,
                                src.company_nam,
                                src.trade_nam,
                                src.url,
                                src.company_department,
                                src.profession,
                                src.enable_affiliation,
                                src.affiliated_with,
                                src.reg_number_type,
                                src.reg_number,
                                src.reg_details,
                                src.affiliation_type,
                                src.client_number,
                                src.itn,
                                src.tax_position,
                                src.country,
                                src.state,
                                src.city,
                                src.address_zip,
                                src.address_line_1,
                                src.address_line_2,
                                src.address_line_3,
                                src.address_line_4,
                                src.phone,
                                src.phone_h,
                                src.phone_m,
                                src.fax,
                                src.fax_h,
                                src.e_mail,
                                src.delivery_type,
                                src.date_expire,
                                src.date_open,
                                src.gender,
                                src.language,
                                src.marital_status,
                                src.tr_title,
                                src.tr_first_nam,
                                src.tr_last_nam,
                                src.tr_company_nam,
                                src.add_date_01,
                                src.add_date_02,
                                src.add_info_01,
                                src.add_info_02,
                                src.add_info_03,
                                src.add_info_04,
                                src.is_ready);
                    COMMIT;
                END IF;
            ELSE    DELETE FROM sync_way4_client
                    WHERE id = orchestrate_before_id;
                    COMMIT;
            END IF;

        END IF;

    EXCEPTION
        WHEN OTHERS THEN
            ROLLBACK;
            l_err_desc := SUBSTR( sqlerrm, 1, 200);

            cspks_cdc_util.pr_log_sync_error('SIBS', 'CLIENT', 'SYNC_WAY4_CLIENT',
                                                    orchestrate_id, dm_operation_type, l_err_desc);
            COMMIT;
            RAISE;
    END;

 /*----------------------------------------------------------------------------------------------------
 **  Description:
 **
 **  MODIFICATION HISTORY
 **  Person      Date           Comments
 **  ThanhNT      23/01/2015    Created

----------------------------------------------------------------------------------------------------*/

    PROCEDURE pr_acnt_contract_sync(dm_operation_type                IN CHAR,
                                    orchestrate_amnd_date            IN DATE,
                                    orchestrate_amnd_state           IN VARCHAR2,
                                    orchestrate_amnd_officer         IN NUMBER,
                                    orchestrate_amnd_prev            IN NUMBER,
                                    orchestrate_id                   IN NUMBER,
                                    orchestrate_pcat                 IN VARCHAR2,
                                    orchestrate_con_cat              IN VARCHAR2,
                                    orchestrate_terminal_category    IN VARCHAR2,
                                    orchestrate_ccat                 IN VARCHAR2,
                                    orchestrate_f_i                  IN NUMBER,
                                    orchestrate_branch               IN VARCHAR2,
                                    orchestrate_service_group        IN VARCHAR2,
                                    orchestrate_contract_number      IN VARCHAR2,
                                    orchestrate_contract_name        IN VARCHAR2,
                                    orchestrate_comment_text         IN VARCHAR2,
                                    orchestrate_base_relation        IN VARCHAR2,
                                    orchestrate_relation_tag         IN VARCHAR2,
                                    orchestrate_acnt_contract__id    IN NUMBER,
                                    orchestrate_contr_type           IN NUMBER,
                                    orchestrate_contr_subtype__id    IN NUMBER,
                                    orchestrate_serv_pack__id        IN NUMBER,
                                    orchestrate_old_pack             IN NUMBER,
                                    orchestrate_channel              IN VARCHAR2,
                                    orchestrate_acc_scheme__id       IN NUMBER,
                                    orchestrate_old_scheme           IN NUMBER,
                                    orchestrate_product              IN VARCHAR2,
                                    orchestrate_product_prev         IN VARCHAR2,
                                    orchestrate_parent_product       IN VARCHAR2,
                                    orchestrate_main_product         IN NUMBER,
                                    orchestrate_client__id           IN NUMBER,
                                    orchestrate_client_type          IN NUMBER,
                                    orchestrate_acnt_contract__oid   IN NUMBER,
                                    orchestrate_liab_category        IN VARCHAR2,
                                    orchestrate_liab_contract        IN NUMBER,
                                    orchestrate_liab_contract_prev   IN NUMBER,
                                    orchestrate_billing_contract     IN NUMBER,
                                    orchestrate_behavior_group       IN NUMBER,
                                    orchestrate_behavior_type        IN NUMBER,
                                    orchestrate_behavior_type_prev   IN NUMBER,
                                    orchestrate_check_available      IN VARCHAR2,
                                    orchestrate_check_usage          IN VARCHAR2,
                                    orchestrate_curr                 IN VARCHAR2,
                                    orchestrate_old_curr             IN VARCHAR2,
                                    orchestrate_auth_limit_amount    IN NUMBER,
                                    orchestrate_base_auth_limit      IN NUMBER,
                                    orchestrate_liab_balance         IN NUMBER,
                                    orchestrate_liab_blocked         IN NUMBER,
                                    orchestrate_own_balance          IN NUMBER,
                                    orchestrate_own_blocked          IN NUMBER,
                                    orchestrate_sub_balance          IN NUMBER,
                                    orchestrate_sub_blocked          IN NUMBER,
                                    orchestrate_total_blocked        IN NUMBER,
                                    orchestrate_total_balance        IN NUMBER,
                                    orchestrate_shared_balance       IN NUMBER,
                                    orchestrate_shared_blocked       IN NUMBER,
                                    orchestrate_amount_available     IN NUMBER,
                                    orchestrate_date_open            IN DATE,
                                    orchestrate_date_expire          IN DATE,
                                    orchestrate_last_billing_date    IN DATE,
                                    orchestrate_next_billing_date    IN DATE,
                                    orchestrate_last_scan            IN DATE,
                                    orchestrate_card_expire          IN VARCHAR2,
                                    orchestrate_production_status    IN VARCHAR2,
                                    orchestrate_rbs_member_id        IN VARCHAR2,
                                    orchestrate_rbs_number           IN VARCHAR2,
                                    orchestrate_report_type          IN VARCHAR2,
                                    orchestrate_max_pin_attempts     IN NUMBER,
                                    orchestrate_pin_attempts         IN NUMBER,
                                    orchestrate_chip_scheme          IN NUMBER,
                                    orchestrate_risk_scheme          IN NUMBER,
                                    orchestrate_risk_factor          IN NUMBER,
                                    orchestrate_risk_factor_prev     IN NUMBER,
                                    orchestrate_contr_status         IN NUMBER,
                                    orchestrate_merchant_id          IN VARCHAR2,
                                    orchestrate_tr_title             IN NUMBER,
                                    orchestrate_tr_company           IN VARCHAR2,
                                    orchestrate_tr_country           IN VARCHAR2,
                                    orchestrate_tr_first_nam         IN VARCHAR2,
                                    orchestrate_tr_last_nam          IN VARCHAR2,
                                    orchestrate_tr_sic               IN VARCHAR2,
                                    orchestrate_add_info_01          IN VARCHAR2,
                                    orchestrate_add_info_02          IN VARCHAR2,
                                    orchestrate_add_info_03          IN VARCHAR2,
                                    orchestrate_add_info_04          IN VARCHAR2,
                                    orchestrate_contract_level       IN VARCHAR2,
                                    orchestrate_ext_data             IN VARCHAR2,
                                    orchestrate_report_address       IN NUMBER,
                                    orchestrate_share_balance        IN VARCHAR2,
                                    orchestrate_is_multycurrency     IN VARCHAR2,
                                    orchestrate_enables_item         IN VARCHAR2,
                                    orchestrate_cycle_length         IN NUMBER,
                                    orchestrate_interval_type        IN VARCHAR2,
                                    orchestrate_status_category      IN VARCHAR2,
                                    orchestrate_limit_is_active      IN VARCHAR2,
                                    orchestrate_settlement_type      IN VARCHAR2,
                                    orchestrate_is_ready             IN VARCHAR2,
                                    orchestrate_before_id            IN NUMBER)
IS
        l_check NUMBER(2);
        l_err_desc VARCHAR2(250);

    BEGIN

        IF orchestrate_amnd_state = 'A' THEN
            IF dm_operation_type <> 'D'
            THEN

                --Todo: Check xem client nay co thuoc CIF tren EBANK khong?
                SELECT CASE WHEN EXISTS(SELECT 1
                                        FROM sync_way4_client clt,
                                            (SELECT DISTINCT cif_no
                                            FROM   bc_user_info
                                            UNION
                                            SELECT distinct cif_no
                                            FROM   bb_corp_info
                                            )cif
                                        WHERE clt.id = orchestrate_client__id
                                        AND clt.client_number = cif.cif_no)
                            THEN 1
                            ELSE 0
                        END
                INTO l_check FROM dual;

                --Todo: Merge thong tin

                IF l_check = 1 THEN
                    MERGE INTO sync_way4_acnt_contract  c
                    USING (SELECT orchestrate_amnd_date             AS amnd_date,
                                orchestrate_amnd_state            AS amnd_state,
                                orchestrate_amnd_officer          AS amnd_officer,
                                orchestrate_amnd_prev             AS amnd_prev,
                                orchestrate_id                    AS id,
                                orchestrate_pcat                  AS pcat,
                                orchestrate_con_cat               AS con_cat,
                                orchestrate_terminal_category     AS terminal_category,
                                orchestrate_ccat                  AS ccat,
                                orchestrate_f_i                   AS f_i,
                                orchestrate_branch                AS branch,
                                orchestrate_service_group         AS service_group,
                                orchestrate_contract_number       AS contract_number,
                                orchestrate_contract_name         AS contract_name,
                                orchestrate_comment_text          AS comment_text,
                                orchestrate_base_relation         AS base_relation,
                                orchestrate_relation_tag          AS relation_tag,
                                orchestrate_acnt_contract__id     AS acnt_contract__id,
                                orchestrate_contr_type            AS contr_type,
                                orchestrate_contr_subtype__id     AS contr_subtype__id,
                                orchestrate_serv_pack__id         AS serv_pack__id,
                                orchestrate_old_pack              AS old_pack,
                                orchestrate_channel               AS channel,
                                orchestrate_acc_scheme__id        AS acc_scheme__id,
                                orchestrate_old_scheme            AS old_scheme,
                                orchestrate_product               AS product,
                                orchestrate_product_prev          AS product_prev,
                                orchestrate_parent_product        AS parent_product,
                                orchestrate_main_product          AS main_product,
                                orchestrate_client__id            AS client__id,
                                orchestrate_client_type           AS client_type,
                                orchestrate_acnt_contract__oid    AS acnt_contract__oid,
                                orchestrate_liab_category         AS liab_category,
                                orchestrate_liab_contract         AS liab_contract,
                                orchestrate_liab_contract_prev    AS liab_contract_prev,
                                orchestrate_billing_contract      AS billing_contract,
                                orchestrate_behavior_group        AS behavior_group,
                                orchestrate_behavior_type         AS behavior_type,
                                orchestrate_behavior_type_prev    AS behavior_type_prev,
                                orchestrate_check_available       AS check_available,
                                orchestrate_check_usage           AS check_usage,
                                orchestrate_curr                  AS curr,
                                orchestrate_old_curr              AS old_curr,
                                orchestrate_auth_limit_amount     AS auth_limit_amount,
                                orchestrate_base_auth_limit       AS base_auth_limit,
                                orchestrate_liab_balance          AS liab_balance,
                                orchestrate_liab_blocked          AS liab_blocked,
                                orchestrate_own_balance           AS own_balance,
                                orchestrate_own_blocked           AS own_blocked,
                                orchestrate_sub_balance           AS sub_balance,
                                orchestrate_sub_blocked           AS sub_blocked,
                                orchestrate_total_blocked         AS total_blocked,
                                orchestrate_total_balance         AS total_balance,
                                orchestrate_shared_balance        AS shared_balance,
                                orchestrate_shared_blocked        AS shared_blocked,
                                orchestrate_amount_available      AS amount_available,
                                orchestrate_date_open             AS date_open,
                                orchestrate_date_expire           AS date_expire,
                                orchestrate_last_billing_date     AS last_billing_date,
                                orchestrate_next_billing_date     AS next_billing_date,
                                orchestrate_last_scan             AS last_scan,
                                orchestrate_card_expire           AS card_expire,
                                orchestrate_production_status     AS production_status,
                                orchestrate_rbs_member_id         AS rbs_member_id,
                                orchestrate_rbs_number            AS rbs_number,
                                orchestrate_report_type           AS report_type,
                                orchestrate_max_pin_attempts      AS max_pin_attempts,
                                orchestrate_pin_attempts          AS pin_attempts,
                                orchestrate_chip_scheme           AS chip_scheme,
                                orchestrate_risk_scheme           AS risk_scheme,
                                orchestrate_risk_factor           AS risk_factor,
                                orchestrate_risk_factor_prev      AS risk_factor_prev,
                                orchestrate_contr_status          AS contr_status,
                                orchestrate_merchant_id           AS merchant_id,
                                orchestrate_tr_title              AS tr_title,
                                orchestrate_tr_company            AS tr_company,
                                orchestrate_tr_country            AS tr_country,
                                orchestrate_tr_first_nam          AS tr_first_nam,
                                orchestrate_tr_last_nam           AS tr_last_nam,
                                orchestrate_tr_sic                AS tr_sic,
                                orchestrate_add_info_01           AS add_info_01,
                                orchestrate_add_info_02           AS add_info_02,
                                orchestrate_add_info_03           AS add_info_03,
                                orchestrate_add_info_04           AS add_info_04,
                                orchestrate_contract_level        AS contract_level,
                                orchestrate_ext_data              AS ext_data,
                                orchestrate_report_address        AS report_address,
                                orchestrate_share_balance         AS share_balance,
                                orchestrate_is_multycurrency      AS is_multycurrency,
                                orchestrate_enables_item          AS enables_item,
                                orchestrate_cycle_length          AS cycle_length,
                                orchestrate_interval_type         AS interval_type,
                                orchestrate_status_category       AS status_category,
                                orchestrate_limit_is_active       AS limit_is_active,
                                orchestrate_settlement_type       AS settlement_type,
                                orchestrate_is_ready              AS is_ready
                          FROM dual) src
                    ON (c.id = src.id)
                    WHEN MATCHED THEN
                        UPDATE
                        SET  c.amnd_date             = src.amnd_date,
                            c.amnd_state            = src.amnd_state,
                            c.amnd_officer          = src.amnd_officer,
                            c.amnd_prev             = src.amnd_prev,
                            c.pcat                  = src.pcat,
                            c.con_cat               = src.con_cat,
                            c.terminal_category     = src.terminal_category,
                            c.ccat                  = src.ccat,
                            c.f_i                   = src.f_i,
                            c.branch                = src.branch,
                            c.service_group         = src.service_group,
                            c.contract_number       = src.contract_number,
                            c.contract_name         = src.contract_name,
                            c.comment_text          = src.comment_text,
                            c.base_relation         = src.base_relation,
                            c.relation_tag          = src.relation_tag,
                            c.acnt_contract__id     = src.acnt_contract__id,
                            c.contr_type            = src.contr_type,
                            c.contr_subtype__id     = src.contr_subtype__id,
                            c.serv_pack__id         = src.serv_pack__id,
                            c.old_pack              = src.old_pack,
                            c.channel               = src.channel,
                            c.acc_scheme__id        = src.acc_scheme__id,
                            c.old_scheme            = src.old_scheme,
                            c.product               = src.product,
                            c.product_prev          = src.product_prev,
                            c.parent_product        = src.parent_product,
                            c.main_product          = src.main_product,
                            c.client__id            = src.client__id,
                            c.client_type           = src.client_type,
                            c.acnt_contract__oid    = src.acnt_contract__oid,
                            c.liab_category         = src.liab_category,
                            c.liab_contract         = src.liab_contract,
                            c.liab_contract_prev    = src.liab_contract_prev,
                            c.billing_contract      = src.billing_contract,
                            c.behavior_group        = src.behavior_group,
                            c.behavior_type         = src.behavior_type,
                            c.behavior_type_prev    = src.behavior_type_prev,
                            c.check_available       = src.check_available,
                            c.check_usage           = src.check_usage,
                            c.curr                  = src.curr,
                            c.old_curr              = src.old_curr,
                            c.auth_limit_amount     = src.auth_limit_amount,
                            c.base_auth_limit       = src.base_auth_limit,
                            c.liab_balance          = src.liab_balance,
                            c.liab_blocked          = src.liab_blocked,
                            c.own_balance           = src.own_balance,
                            c.own_blocked           = src.own_blocked,
                            c.sub_balance           = src.sub_balance,
                            c.sub_blocked           = src.sub_blocked,
                            c.total_blocked         = src.total_blocked,
                            c.total_balance         = src.total_balance,
                            c.shared_balance        = src.shared_balance,
                            c.shared_blocked        = src.shared_blocked,
                            c.amount_available      = src.amount_available,
                            c.date_open             = src.date_open,
                            c.date_expire           = src.date_expire,
                            c.last_billing_date     = src.last_billing_date,
                            c.next_billing_date     = src.next_billing_date,
                            c.last_scan             = src.last_scan,
                            c.card_expire           = src.card_expire,
                            c.production_status     = src.production_status,
                            c.rbs_member_id         = src.rbs_member_id,
                            c.rbs_number            = src.rbs_number,
                            c.report_type           = src.report_type,
                            c.max_pin_attempts      = src.max_pin_attempts,
                            c.pin_attempts          = src.pin_attempts,
                            c.chip_scheme           = src.chip_scheme,
                            c.risk_scheme           = src.risk_scheme,
                            c.risk_factor           = src.risk_factor,
                            c.risk_factor_prev      = src.risk_factor_prev,
                            c.contr_status          = src.contr_status,
                            c.merchant_id           = src.merchant_id,
                            c.tr_title              = src.tr_title,
                            c.tr_company            = src.tr_company,
                            c.tr_country            = src.tr_country,
                            c.tr_first_nam          = src.tr_first_nam,
                            c.tr_last_nam           = src.tr_last_nam,
                            c.tr_sic                = src.tr_sic,
                            c.add_info_01           = src.add_info_01,
                            c.add_info_02           = src.add_info_02,
                            c.add_info_03           = src.add_info_03,
                            c.add_info_04           = src.add_info_04,
                            c.contract_level        = src.contract_level,
                            c.ext_data              = src.ext_data,
                            c.report_address        = src.report_address,
                            c.share_balance         = src.share_balance,
                            c.is_multycurrency      = src.is_multycurrency,
                            c.enables_item          = src.enables_item,
                            c.cycle_length          = src.cycle_length,
                            c.interval_type         = src.interval_type,
                            c.status_category       = src.status_category,
                            c.limit_is_active       = src.limit_is_active,
                            c.settlement_type       = src.settlement_type,
                            c.is_ready              = src.is_ready
                    WHEN NOT MATCHED THEN
                        INSERT (amnd_date,
                                amnd_state,
                                amnd_officer,
                                amnd_prev,
                                id,
                                pcat,
                                con_cat,
                                terminal_category,
                                ccat,
                                f_i,
                                branch,
                                service_group,
                                contract_number,
                                contract_name,
                                comment_text,
                                base_relation,
                                relation_tag,
                                acnt_contract__id,
                                contr_type,
                                contr_subtype__id,
                                serv_pack__id,
                                old_pack,
                                channel,
                                acc_scheme__id,
                                old_scheme,
                                product,
                                product_prev,
                                parent_product,
                                main_product,
                                client__id,
                                client_type,
                                acnt_contract__oid,
                                liab_category,
                                liab_contract,
                                liab_contract_prev,
                                billing_contract,
                                behavior_group,
                                behavior_type,
                                behavior_type_prev,
                                check_available,
                                check_usage,
                                curr,
                                old_curr,
                                auth_limit_amount,
                                base_auth_limit,
                                liab_balance,
                                liab_blocked,
                                own_balance,
                                own_blocked,
                                sub_balance,
                                sub_blocked,
                                total_blocked,
                                total_balance,
                                shared_balance,
                                shared_blocked,
                                amount_available,
                                date_open,
                                date_expire,
                                last_billing_date,
                                next_billing_date,
                                last_scan,
                                card_expire,
                                production_status,
                                rbs_member_id,
                                rbs_number,
                                report_type,
                                max_pin_attempts,
                                pin_attempts,
                                chip_scheme,
                                risk_scheme ,
                                risk_factor,
                                risk_factor_prev,
                                contr_status,
                                merchant_id,
                                tr_title,
                                tr_company,
                                tr_country,
                                tr_first_nam,
                                tr_last_nam,
                                tr_sic,
                                add_info_01,
                                add_info_02,
                                add_info_03,
                                add_info_04,
                                contract_level,
                                ext_data,
                                report_address,
                                share_balance,
                                is_multycurrency,
                                enables_item,
                                cycle_length,
                                interval_type,
                                status_category,
                                limit_is_active,
                                settlement_type,
                                is_ready)
                        VALUES (src.amnd_date,
                                src.amnd_state,
                                src.amnd_officer,
                                src.amnd_prev,
                                src.id,
                                src.pcat,
                                src.con_cat,
                                src.terminal_category,
                                src.ccat,
                                src.f_i,
                                src.branch,
                                src.service_group,
                                src.contract_number,
                                src.contract_name,
                                src.comment_text,
                                src.base_relation,
                                src.relation_tag,
                                src.acnt_contract__id,
                                src.contr_type,
                                src.contr_subtype__id,
                                src.serv_pack__id,
                                src.old_pack,
                                src.channel,
                                src.acc_scheme__id,
                                src.old_scheme,
                                src.product,
                                src.product_prev,
                                src.parent_product,
                                src.main_product,
                                src.client__id,
                                src.client_type,
                                src.acnt_contract__oid,
                                src.liab_category,
                                src.liab_contract,
                                src.liab_contract_prev,
                                src.billing_contract,
                                src.behavior_group,
                                src.behavior_type,
                                src.behavior_type_prev,
                                src.check_available,
                                src.check_usage,
                                src.curr,
                                src.old_curr,
                                src.auth_limit_amount,
                                src.base_auth_limit,
                                src.liab_balance,
                                src.liab_blocked,
                                src.own_balance,
                                src.own_blocked,
                                src.sub_balance,
                                src.sub_blocked,
                                src.total_blocked,
                                src.total_balance,
                                src.shared_balance,
                                src.shared_blocked,
                                src.amount_available,
                                src.date_open,
                                src.date_expire,
                                src.last_billing_date,
                                src.next_billing_date,
                                src.last_scan,
                                src.card_expire,
                                src.production_status,
                                src.rbs_member_id,
                                src.rbs_number,
                                src.report_type,
                                src.max_pin_attempts,
                                src.pin_attempts,
                                src.chip_scheme,
                                src.risk_scheme ,
                                src.risk_factor,
                                src.risk_factor_prev,
                                src.contr_status,
                                src.merchant_id,
                                src.tr_title,
                                src.tr_company,
                                src.tr_country,
                                src.tr_first_nam,
                                src.tr_last_nam,
                                src.tr_sic,
                                src.add_info_01,
                                src.add_info_02,
                                src.add_info_03,
                                src.add_info_04,
                                src.contract_level,
                                src.ext_data,
                                src.report_address,
                                src.share_balance,
                                src.is_multycurrency,
                                src.enables_item,
                                src.cycle_length,
                                src.interval_type,
                                src.status_category,
                                src.limit_is_active,
                                src.settlement_type,
                                src.is_ready);
                    COMMIT;
                END IF;
            ELSE DELETE FROM sync_way4_acnt_contract
                    WHERE id = orchestrate_before_id;
                    COMMIT;
            END IF;
        END IF;

    EXCEPTION
        WHEN OTHERS THEN
            ROLLBACK;
            l_err_desc := SUBSTR( sqlerrm, 1, 200);

            cspks_cdc_util.pr_log_sync_error('SIBS', 'ACNT_CONTRACT', 'SYNC_WAY4_ACNT_CONTRACT',
                                                    orchestrate_id, dm_operation_type, l_err_desc);
            COMMIT;
            RAISE;
    END;

/*
BEGIN
    SELECT   *
    INTO   logrow
    FROM   tlogdebug
    WHERE   ROWNUM <= 1;

    pkgctx      :=
    plog.init('cspkg_account_sync',
        plevel => logrow.loglevel,
        plogtable => ( logrow.log4table = 'Y' ),
        palert => ( logrow.log4alert = 'Y' ),
        ptrace => ( logrow.log4trace = 'Y' ) );*/
END;

/
