--------------------------------------------------------
--  DDL for Package PK_PROCESS_DATA
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "IBS"."PK_PROCESS_DATA" AS 

  /* TODO enter package declarations (types, exceptions, methods etc) here */ 
  PROCEDURE UPDATE_CUSTOMER_MOBILE_PAYMENT;
  
  PROCEDURE UPDATE_MOBILE_PREPAID;
  
  PROCEDURE UPDATE_BENEFIT_TRANSFER;

  PROCEDURE UPDATE_EMAIL_USER_INFO;

  PROCEDURE UPDATE_RELATED_ACCOUNT;

  PROCEDURE CONVERT_MOBILE_BC_USER_INFO;

  PROCEDURE CONVERT_MOBILE_BB_USER_INFO;

  PROCEDURE CONVERT_MOBILE_BILL_PAYMENT;
  
  PROCEDURE CONVERT_DATA_WORKFLOW_ACTIVITI;
  
  PROCEDURE CALCULATE_PROMOTION_EVERYDAY;
  
  PROCEDURE UPDATE_DEFAULT_WORKFLOW;
  
  PROCEDURE UPDATE_ACCT_TYPE_RELATED;
  
  PROCEDURE CALCULATE_CIF_NO_FROM_CORE;
  
  PROCEDURE UPDATE_CIF_NO_FROM_CORE;
  
  PROCEDURE PROCESS_CAPTCHA;
  
  PROCEDURE WORD_GAME_SET_SEQUENCE(p_seq_name in varchar2);
  
  PROCEDURE SYNC_DATA_BK_CIF;
  
  PROCEDURE SYNC_DATA_BK_CIF_CORP;
  
END PK_PROCESS_DATA;

/
