--------------------------------------------------------
--  File created - Monday-December-11-2023   
--------------------------------------------------------
@C:\Users\tuantv9\Packages body\export.sql\ACSPKG_BENIFIT_REFRESH_MANUAL.sql
@C:\Users\tuantv9\Packages body\export.sql\BILL_PAYMENT_BEGIN_DAY.sql
@C:\Users\tuantv9\Packages body\export.sql\BILL_RESET_LIMIT_RECHARGE.sql
@C:\Users\tuantv9\Packages body\export.sql\CSPKG_ACCOUNT_ETL_SYNC.sql
@C:\Users\tuantv9\Packages body\export.sql\CSPKG_ACCOUNT_ETL_SYNC_DEV_MDB.sql
@C:\Users\tuantv9\Packages body\export.sql\CSPKG_ACCOUNT_SYNC.sql
@C:\Users\tuantv9\Packages body\export.sql\CSPKG_ACCOUNT_SYNC_247.sql
@C:\Users\tuantv9\Packages body\export.sql\CSPKG_ACCOUNT_SYNC_DEV.sql
@C:\Users\tuantv9\Packages body\export.sql\CSPKG_ACCOUNT_SYNC_DEV_MDB.sql
@C:\Users\tuantv9\Packages body\export.sql\CSPKG_ACCOUNT_SYNC_DEV_THANH.sql
@C:\Users\tuantv9\Packages body\export.sql\CSPKG_ACCOUNT_SYNC_MANUAL.sql
@C:\Users\tuantv9\Packages body\export.sql\CSPKG_BALANCE_PERIOD_SYNC.sql
@C:\Users\tuantv9\Packages body\export.sql\CSPKG_BALANCE_PERIOD_SYNC_TEMP.sql
@C:\Users\tuantv9\Packages body\export.sql\CSPKG_BENIFIT_REFRESH.sql
@C:\Users\tuantv9\Packages body\export.sql\CSPKG_BENIFIT_REFRESH_247.sql
@C:\Users\tuantv9\Packages body\export.sql\CSPKG_BENIFIT_REFRESH_BATCH.sql
@C:\Users\tuantv9\Packages body\export.sql\CSPKG_BENIFIT_REFRESH_MANUAL.sql
@C:\Users\tuantv9\Packages body\export.sql\CSPKG_CIF_SYNC.sql
@C:\Users\tuantv9\Packages body\export.sql\CSPKG_CLEAR.sql
@C:\Users\tuantv9\Packages body\export.sql\CSPKG_CLEAR_TF_SML_TRANSFER.sql
@C:\Users\tuantv9\Packages body\export.sql\CSPKG_DATA_LATER_PROCESS.sql
@C:\Users\tuantv9\Packages body\export.sql\CSPKG_GWSERVICE_SYNC.sql
@C:\Users\tuantv9\Packages body\export.sql\CSPKG_PARAM_SYNC.sql
@C:\Users\tuantv9\Packages body\export.sql\CSPKG_TRANSACTION_ETL_SYNC.sql
@C:\Users\tuantv9\Packages body\export.sql\CSPKG_TRANSACTION_ETL_SYNC_2.sql
@C:\Users\tuantv9\Packages body\export.sql\CSPKG_TRANSACTION_ETL_SYNC_DEV.sql
@C:\Users\tuantv9\Packages body\export.sql\CSPKG_TRANSACTION_SYNC.sql
@C:\Users\tuantv9\Packages body\export.sql\CSPKG_TRANSACTION_SYNC_247.sql
@C:\Users\tuantv9\Packages body\export.sql\CSPKG_TRANSACTION_SYNC_DEV.sql
@C:\Users\tuantv9\Packages body\export.sql\CSPKS_CDC_BIZ_COMMON.sql
@C:\Users\tuantv9\Packages body\export.sql\CSPKS_CDC_UTIL.sql
@C:\Users\tuantv9\Packages body\export.sql\CSPKS_ETL.sql
@C:\Users\tuantv9\Packages body\export.sql\CSPKS_UTIL.sql
@C:\Users\tuantv9\Packages body\export.sql\EBANK_ACCOUNT_SYNC.sql
@C:\Users\tuantv9\Packages body\export.sql\EBANK_CARD_SYNC.sql
@C:\Users\tuantv9\Packages body\export.sql\EBANK_CIF_SYNC.sql
@C:\Users\tuantv9\Packages body\export.sql\EBANK_COMMON_SYNC.sql
@C:\Users\tuantv9\Packages body\export.sql\EBANK_DWH_SYNC.sql
@C:\Users\tuantv9\Packages body\export.sql\EBANK_PARAM_SYNC.sql
@C:\Users\tuantv9\Packages body\export.sql\EBANK_STAGING_TRANSACTION_SYNC.sql
@C:\Users\tuantv9\Packages body\export.sql\EBANK_SYNC_UTIL.sql
@C:\Users\tuantv9\Packages body\export.sql\EBANK_TF_SYNC.sql
@C:\Users\tuantv9\Packages body\export.sql\EBANK_TRANSACTION_SYNC.sql
@C:\Users\tuantv9\Packages body\export.sql\GW_PK_LIB.sql
@C:\Users\tuantv9\Packages body\export.sql\GW_PK_VCB_REPORT.sql
@C:\Users\tuantv9\Packages body\export.sql\JOB_REMOVE_ACC_BEAUTITY_IB.sql
@C:\Users\tuantv9\Packages body\export.sql\JOB_REMOVE_EKYC_RETRY.sql
@C:\Users\tuantv9\Packages body\export.sql\MOVE_DATA_TRANSFER_HIS.sql
@C:\Users\tuantv9\Packages body\export.sql\PKG_IB_SYNC_TMP.sql
@C:\Users\tuantv9\Packages body\export.sql\PKG_MSB_BC_ONL_SAV.sql
@C:\Users\tuantv9\Packages body\export.sql\PKG_MSB_BC_REG_API.sql
@C:\Users\tuantv9\Packages body\export.sql\PKG_MSB_UTIL.sql
@C:\Users\tuantv9\Packages body\export.sql\PK_ACTIVITI_PROCESS.sql
@C:\Users\tuantv9\Packages body\export.sql\PK_DISCOUNT_PROCESS.sql
@C:\Users\tuantv9\Packages body\export.sql\PK_MIGRATE_DATA.sql
@C:\Users\tuantv9\Packages body\export.sql\PK_PROCESS_CIF.sql
@C:\Users\tuantv9\Packages body\export.sql\PK_PROCESS_DATA.sql
@C:\Users\tuantv9\Packages body\export.sql\PK_PROCESS_EKYC.sql
@C:\Users\tuantv9\Packages body\export.sql\PK_PROCESS_FD.sql
@C:\Users\tuantv9\Packages body\export.sql\PK_SYNC_DATA.sql
@C:\Users\tuantv9\Packages body\export.sql\PK_SYNC_RATE.sql
@C:\Users\tuantv9\Packages body\export.sql\PK_UAT_INIT_DATA.sql
@C:\Users\tuantv9\Packages body\export.sql\PK_UPDATE_DATA.sql
@C:\Users\tuantv9\Packages body\export.sql\PK_UPDATE_STATUS_BOND.sql
@C:\Users\tuantv9\Packages body\export.sql\PK_UPDATE_STATUS_LOAN.sql
@C:\Users\tuantv9\Packages body\export.sql\PK_WORKFLOW_PROCESS.sql
@C:\Users\tuantv9\Packages body\export.sql\SYNC_HANDLE_CDTNEW.sql
@C:\Users\tuantv9\Packages body\export.sql\SYNC_WAY4_DATA.sql
@C:\Users\tuantv9\Packages body\export.sql\SYNC_WAY4_DATA_DOC.sql
@C:\Users\tuantv9\Packages body\export.sql\SYS_DATA_IB.sql
@C:\Users\tuantv9\Packages body\export.sql\VHNHDT.sql
@C:\Users\tuantv9\Packages body\export.sql\W4PKG_DATA_ETL_SYNC.sql
@C:\Users\tuantv9\Packages body\export.sql\W4PKG_DATA_SYNC.sql
